### ISSUE TITLE
De-serialization should respect requiredness as much as serialization

### ISSUE THREAD

**Issue by lsb** [ruby-protobuf/protobuf#243]
Given the following Protobuf:

```
class TwoBools < ::Protobuf::Message ; end
class TwoBools ; required :bool, :b1, 1 ; required :bool, :b2, 2 ; end
```

when I do TwoBools.encode(:b1 => false) I get a Protobuf::SerializationError, which I expect.

However, I can mangle the protobuf and truncate it.

When I do TwoBools.decode("\x10\x00") I get {:b2=>false}, which I didn't expect; I would have expected a DeserializationError.

Is this asymmetry intentional?

**Comment by abrandoned** [comment]
this is not intentional

**Comment by phrinx** [comment]
I think in general 'protobuf' gems handles decoding very poorly. Another example:

```
○ → gem install protobuf
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: minitest-5.7.0.gem (100%)
Successfully installed minitest-5.7.0
Fetching: tzinfo-1.2.2.gem (100%)
Successfully installed tzinfo-1.2.2
Fetching: i18n-0.7.0.gem (100%)
Successfully installed i18n-0.7.0
Fetching: activesupport-4.2.3.rc1.gem (100%)
Successfully installed activesupport-4.2.3.rc1
Fetching: middleware-0.1.0.gem (100%)
Successfully installed middleware-0.1.0
Fetching: thor-0.19.1.gem (100%)
Successfully installed thor-0.19.1
Fetching: protobuf-3.5.0.gem (100%)
Successfully installed protobuf-3.5.0
8 gems installed
○ → irb
2.1.1 :001 > require 'protobuf'
 => true
2.1.1 :002 > class HelloWorld < ::Protobuf::Message ; end
 => nil
2.1.1 :003 > class HelloWorld ; required :string, :str, 1 ; end
 => :str!
2.1.1 :004 >  (HelloWorld.decode 'A').str
 => nil
2.1.1 :005 > (HelloWorld.decode 'A').encode
Protobuf::SerializationError: Required field HelloWorld#str does not have a value.
	from /Users/dkoehler/.rvm/gems/ruby-2.1.1@protobuf/gems/protobuf-3.5.0/lib/protobuf/message.rb:78:in `block in each_field_for_serialization'
	from /Users/dkoehler/.rvm/gems/ruby-2.1.1@protobuf/gems/protobuf-3.5.0/lib/protobuf/message.rb:72:in `each'
	from /Users/dkoehler/.rvm/gems/ruby-2.1.1@protobuf/gems/protobuf-3.5.0/lib/protobuf/message.rb:72:in `each_field_for_serialization'
	from /Users/dkoehler/.rvm/gems/ruby-2.1.1@protobuf/gems/protobuf-3.5.0/lib/protobuf/encoder.rb:26:in `encode'
	from /Users/dkoehler/.rvm/gems/ruby-2.1.1@protobuf/gems/protobuf-3.5.0/lib/protobuf/encoder.rb:5:in `encode'
	from /Users/dkoehler/.rvm/gems/ruby-2.1.1@protobuf/gems/protobuf-3.5.0/lib/protobuf/message/serialization.rb:60:in `encode_to'
	from /Users/dkoehler/.rvm/gems/ruby-2.1.1@protobuf/gems/protobuf-3.5.0/lib/protobuf/message/serialization.rb:53:in `encode'
	from (irb):5
	from /Users/dkoehler/.rvm/rubies/ruby-2.1.1/bin/irb:11:in `<main>'
