### ISSUE TITLE
Cannot compile a basic proto file on Windows

### ISSUE THREAD

**Issue by aogail** [ruby-protobuf/protobuf#320]
I am attempting to switch from the ancient, seemingly unmaintained `ruby_protobuf` gem to this one. Unfortunately, I have run into a roadblock: It appears that `protoc-gen-ruby` does not function on Windows.

I am using `protobuf` 3.6.7 on Windows 7 with Ruby 2.2.3. I have tried `protoc` 2.5 and 2.6.1. I'll list the problems I have hit in order.

The first snag isn't specific to `protoc-gen-ruby`. `protoc` appears to execute its code generators in a way that requires the extension to be specified on Windows, i.e., it does not utilize `%PATHEXT%`. So, the following naive command fails:

```
>protoc -I . --ruby_out ruby foo.proto
--ruby_out: protoc-gen-ruby: The system cannot find the file specified.
```

On Windows, ruby gem binstubs are bat files, so I had to specify the exact name of the protoc-gen-ruby stub.

```
>protoc --plugin=protoc-gen-ruby=c:\Rubies\Ruby223\bin\protoc-gen-ruby.bat -I . --ruby_out ruby foo.proto
```

Next, `protoc-gen-ruby` threw an exception parsing the input from protoc:

```
>type foo.proto
message Foo {
  optional string field = 1;
}

>protoc --plugin=protoc-gen-ruby=c:\Rubies\Ruby223\bin\protoc-gen-ruby.bat -I . --ruby_out ruby foo.proto
c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/decoder.rb:24:in `decode_each_field': 4 (Protobuf::InvalidWireType)
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:41:in `decode_from'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:35:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:11:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/field/message_field.rb:16:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/field/base_field.rb:126:in `set'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:80:in `set_field_bytes'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:42:in `block in decode_from'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/decoder.rb:27:in `decode_each_field'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:41:in `decode_from'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:35:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:11:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/field/message_field.rb:16:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/field/base_field.rb:126:in `set'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:80:in `set_field_bytes'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:42:in `block in decode_from'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/decoder.rb:27:in `decode_each_field'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:41:in `decode_from'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:35:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:11:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/field/message_field.rb:16:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/field/base_field.rb:126:in `set'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:80:in `set_field_bytes'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:42:in `block in decode_from'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/decoder.rb:27:in `decode_each_field'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:41:in `decode_from'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:35:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/message/serialization.rb:11:in `decode'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/lib/protobuf/code_generator.rb:28:in `initialize'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/bin/protoc-gen-ruby:14:in `new'
        from c:/Rubies/Ruby223/lib/ruby/gems/2.2.0/gems/protobuf-3.6.7/bin/protoc-gen-ruby:14:in `<top (required)>'
        from c:/Rubies/Ruby223/bin/protoc-gen-ruby:23:in `load'
        from c:/Rubies/Ruby223/bin/protoc-gen-ruby:23:in `<main>'
--ruby_out: protoc-gen-ruby: Plugin failed with status code 1.
```

Finally, I tried the simplest proto file I could think of. `protoc-gen-ruby` stopped dying, but then `protoc` complained about its output:

```
>type foo.proto
message Foo {
}

>protoc --plugin=protoc-gen-ruby=c:\Rubies\Ruby223\bin\protoc-gen-ruby.bat -I . --ruby_out ruby foo.proto
--ruby_out: protoc-gen-ruby: Plugin output is unparseable: z\303\001\r\n\tfoo.pb.rbz\265\001#encoding: utf-8\r\n\r\n##\r\n#This file is auto-generated. DO NOT EDIT!\r\n#\r\nrequire \'protobuf/message\'\r\n\r\n\r\n##\r\n# Message Classes\r\n#\r\nclass Foo <::Protobuf::Message; end\r\n\r\n\r\n##\r\n# Message Fields\r\n#\r\n
```

Any ideas what could be going wrong?

**Comment by aogail** [comment]
About 10 minutes after I opened this issue I realized that this felt like an encoding issue and lo and behold -- setting binmode for STDIN and STDOUT fixes the problem. PR #321 should fix this issue.
